definitions:
  User:
    type: object
    properties:
      username:
        type: string
      email:
        type: string
      password:
        type: string
        format: password
  UserRole:
    type: object
    properties:
      role:
        type: string
